version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: kritishield-app

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app/backend

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    container_name: kritishield-postgres

    restart: always

    environment:
      POSTGRES_USER: kriti
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kritishield

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: