version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: kritishield-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: kritishield-frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

  postgres:
    image: postgres:16

    container_name: kritishield-postgres

    restart: always

    environment:
      POSTGRES_USER: kriti
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kritishield

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: